---
title: "Dashboard SDR"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(shiny)
library(maps)
library(glue)
library(colourpicker)

detail_national = read_delim("barometre-resultats-detail-national.csv")
indicateur <- detail_national |>
          select(mesure,indicateur,id_indicateur,unite) |>
          distinct(mesure,indicateur,id_indicateur,unite) |>
          arrange(id_indicateur)



synthese_departemental <- readr::read_delim("barometre-resultats-synthese-departemental.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)


mapdata <- map_data("france")
mapdata$region <- tolower(gsub(' ','-',mapdata$region))

synthese_departemental$libelle_departement <- gsub("ô","o",synthese_departemental$libelle_departement)

synthese_departemental$libelle_departement <- iconv(synthese_departemental$libelle_departement,to="ASCII//TRANSLIT")
synthese_departemental$libelle_departement <- gsub("'","",synthese_departemental$libelle_departement)
synthese_departemental$libelle_departement <- tolower(synthese_departemental$libelle_departement)
synthese_departemental$libelle_departement <- gsub("`","",synthese_departemental$libelle_departement)
synthese_departemental$libelle_departement <- tolower(gsub(' ','-',synthese_departemental$libelle_departement))

```

## Column {.sidebar}

```{r}
selectInput(
  "indicateur", label = "Indicateur",
  choices = indicateur$id_indicateur, selected = "taux-deploiement-fibre"

)

  colourInput("colH", label ="Couleur pour les fortes valeurs", "darkorchid4")
  
  colourInput("colL", label ="Couleur pour les faibles valeurs", "coral1")

```

## Column

```{r}

fluidRow(renderPlotly({
  # create ggplot object
  p <-
    ggplot(
      filter(detail_national, id_indicateur == input$indicateur),
      aes(x = date, y = valeur)
    ) +
    geom_line() +
    geom_point() +
    labs(title="Evolution au niveau national")
  
  # wrap ggplot object with ggplotly
  ggplotly(p)
}),
column(8,
renderPlotly({
  
selected_indicator <- indicateur |>
    filter(id_indicateur==input$indicateur)


map2 <- ggplot(left_join(mapdata, filter(synthese_departemental, id_indicateur == input$indicateur), by = c("region" = "libelle_departement")), aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_actuelle),color = "black") + 
  scale_fill_gradient(name=NULL,low=input$colL,high=input$colH,na.value="gray") +
  labs(title = "Synthèse départementale")

ggplotly(map2)
})),
column(4,
       renderText({
       
       glue(" 
       Mesure : 
       {as.character(
         indicateur |>
    filter(id_indicateur==input$indicateur) |>
    select(mesure))}
     ")
         
         
         }),
    
           renderText({glue(" 
       Indicateur : 
       {as.character(
         indicateur |>
    filter(id_indicateur==input$indicateur) |>
    select(indicateur))}
     ")}),
         

               renderText({glue(" 
       Unité : 
       {as.character(
         indicateur |>
    filter(id_indicateur==input$indicateur) |>
    select(unite))}
    ")})
             
    ))

```
