---
title: "Rapport SDR"
output: html_document
date: "2024-01-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

library(plotly)

```

## IMPORT des données

```{r import}
detail_departemental <- readr::read_delim("barometre-resultats-detail-departemental.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)
detail_regional <- readr::read_delim("barometre-resultats-detail-regional.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)
detail_national <- readr::read_delim("barometre-resultats-detail-national.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)
synthese_departemental <- readr::read_delim("barometre-resultats-synthese-departemental.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)
synthese_regional <- readr::read_delim("barometre-resultats-synthese-regional.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)
synthese_national <- readr::read_delim("barometre-resultats-synthese-national.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)

reg_dep <- readr::read_delim("departements-france.csv", delim = ",", trim_ws = TRUE, show_col_types = FALSE)


mapdata <- map_data("france")
mapdata$region <- tolower(gsub(' ','-',mapdata$region))

synthese_departemental$libelle_departement <- iconv(synthese_departemental$libelle_departement,to="ASCII//TRANSLIT")
synthese_departemental$libelle_departement <- gsub("'","",synthese_departemental$libelle_departement)
synthese_departemental$libelle_departement <- tolower(synthese_departemental$libelle_departement)
synthese_departemental$libelle_departement <- tolower(gsub(' ','-',synthese_departemental$libelle_departement))

detail_departemental$libelle_departement <- iconv(detail_departemental$libelle_departement,to="ASCII//TRANSLIT")
detail_departemental$libelle_departement <- gsub("'","",detail_departemental$libelle_departement)
detail_departemental$libelle_departement <- tolower(detail_departemental$libelle_departement)
detail_departemental$libelle_departement <- tolower(gsub(' ','-',detail_departemental$libelle_departement))


mapdata <- map_data("france")

mapdata$region <- iconv(mapdata$region,to="ASCII//TRANSLIT")
mapdata$region <- gsub("'","",mapdata$region)
mapdata$region <- tolower(mapdata$region)
mapdata$region <- tolower(gsub(' ','-',mapdata$region))
```

## 1 jeune 1 solution

```{r 1 jeune 1 solution National}

UnJeuneNational <- detail_national |>
  filter(mesure=="Plan 1 jeune 1 solution") |>
  mutate(recrutés_par_mois = if_else(valeur>lag(valeur), valeur-lag(valeur), valeur, missing=valeur))|>
  rename(recrutés_cumulés = valeur) |>
  pivot_longer(c(recrutés_cumulés, recrutés_par_mois), names_to = "type", values_to = "valeur") |>
  mutate(year = year(date)) |>
  ggplot() + 
  geom_point(mapping=aes(x=date, y=valeur, fg=type)) +
  labs(title = "Jeunes recrutés grâce au projet",
       x = "Date",
       y = "Nombre de recrutement")


plotly::ggplotly(UnJeuneNational)


```

diminution 2020 augmentation 2021-2022 Gros pic en septembre

```{r 1 jeune 1 solution Regions, fig.width=14}

UnJeuneNational <- detail_regional |>
  filter(mesure=="Plan 1 jeune 1 solution" & month(date)==7) |>
  mutate(year = year(date)) |>
  ggplot() + 
  geom_col(mapping = aes(x=libelle_region, y=valeur, bg=libelle_region))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.title.x=element_blank())+
  facet_wrap(vars(year), nrow=1)+
  labs(title = "Jeunes recrutés grâce au projet par région",
       x = "Date",
       y = "Nombre de recrutement",
       bg="Région")

plotly::ggplotly(UnJeuneNational)

```

IDF GOES BRRRRRRR

```{r 1 jeune 1 solution region IdF}

UnJeuneIdF <- detail_regional |>
  filter(mesure=="Plan 1 jeune 1 solution" & code_region=="11") |>
  mutate(valeur_mois = if_else(valeur>lag(valeur), valeur-lag(valeur), valeur, missing=valeur))|>
  mutate(year = year(date)) |>
  ggplot() + 
  geom_point(mapping=aes(x=month(date), y=valeur_mois)) +
  facet_wrap(vars(year), nrow=1)+
  labs(title = "Jeunes recrutés grâce au projet en Île de France",
       x = "Date",
       y = "Nombre de recrutement")

plotly::ggplotly(UnJeuneIdF)


```

```{r 1 jeune 1 solution départements IdF}

UnJeuneDepIdF <- detail_departemental |>
  left_join(reg_dep, by = c("code_departement"="code_departement"))|>
  filter(mesure=="Plan 1 jeune 1 solution" & code_region=="11")|>
  mutate(valeur_mois = if_else(valeur>lag(valeur), valeur-lag(valeur), valeur, missing=valeur))|>
  mutate(year = year(date)) |>
  ggplot() + 
  geom_point(mapping=aes(x=month(date), y=valeur_mois))+
  facet_grid(vars(nom_departement), vars(year), scales="fixed")

plotly::ggplotly(UnJeuneDepIdF)

```

Faire des Cartes :

```{r}
#import carte de la France


#view(mapdata)

#selection indicateurs
ind1 <- filter(synthese_departemental, mesure == "Réduire la mortalité sur les routes")

#Join des deux tableaux
mapdata1 <- left_join(mapdata, ind1, by = c("region" = "libelle_departement"))

map1 <- ggplot(mapdata1, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_actuelle),color = "black")

map2 <- map1 + scale_fill_gradient(name="nombre de morts",low="green",high="red",na.value="gray")

map2
plotly::ggplotly(map2)
```

```{r}
#mapdata3 <- map_data("france")


#reg_dep

mapReg <- left_join(mapdata3, reg_dep, by = c("region" = "nom_departement"))

ind2 <- filter(synthese_regional, mesure == "Réduire la mortalité sur les routes")

regfin <- left_join(mapReg, ind2, by = c("nom_region" = "libelle_region"))

regfin

map5 <- ggplot(regfin, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_actuelle),color = "black")+ 
  scale_fill_gradient(name="nombre de morts",low="green",high="red",na.value="gray")

map5
```

```{r}

indSDF_now_dep <- filter(synthese_departemental, indicateur == "Nombre de personnes sans-abri ou en hébergement ayant obtenu un logement social")

#Join des deux tableaux
mapdataSDF_now_dep <- left_join(mapdata, indSDF_now_dep, by = c("region" = "libelle_departement"))

mapSDF_now_dep <- ggplot(mapdataSDF_now_dep, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_actuelle),color = "black")+ 
  scale_fill_gradient(name="personnes dans l'année*",low="cadetblue1",high="brown2",na.value="gray")

#mapSDF_now_dep
plotly::ggplotly(mapSDF_now_dep)

mapSDF_for_dep <- ggplot(mapdataSDF_now_dep, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_initiale),color = "black")+ 
  scale_fill_gradient(name="personnes dans l'année",low="cadetblue1",high="brown2",na.value="gray")

plotly::ggplotly(mapSDF_for_dep)

indSDF_now_reg <- filter(synthese_regional, mesure == "Nombre de personnes sans-abri ou en hébergement ayant obtenu un logement social")

indSDF_now_dep

regSDF_now_reg <- left_join(mapReg, indSDF_now_reg, by = c("nom_region" = "libelle_region"))

mapSDF_now_reg <- ggplot(regfin, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_actuelle),color = "black")+ 
  scale_fill_gradient(name="personnes dans l'année",low="cadetblue1",high="brown2",na.value="gray")

plotly::ggplotly(mapSDF_now_reg)

mapSDF_for_reg <- ggplot(regfin, aes(x=long, y=lat, group=group)) +
  geom_polygon(aes(fill=valeur_initiale),color = "black")+ 
  scale_fill_gradient(name="personnes dans l'année",low="cadetblue1",high="brown2",na.value="gray")

plotly::ggplotly(mapSDF_for_reg)
```
